<a href="https://colab.research.google.com/github/srichandana498/ML/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
WEEK - 1

In [30]:
## --- 9 ---
import pandas as pd
data = {
    "2014": [100.5, 150.8, 200.9, 30000, 40000],
    "2015": [12000, 18000, 22000, 30000, 45000],
    "2016": [20000, 50000, 70000, 100000, 125000],
    "2017": [50000, 60000, 70000, 80000, 90000]
}
index = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]

sales = pd.DataFrame(data, index=index)
print("Sales DataFrame:\n", sales)


Sales DataFrame:
             2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000


In [31]:
## ---10---
import pandas as pd

#
data = {
    "2014": [100.5, 150.8, 200.9, 30000, 40000],
    "2015": [12000, 18000, 22000, 30000, 45000],
    "2016": [20000, 50000, 70000, 100000, 125000],
    "2017": [50000, 60000, 70000, 80000, 90000]
}
index = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]
sales = pd.DataFrame(data, index=index)

# a)
print("\na)", sales.index.tolist())

# b)
print("\nb)", sales.columns.tolist())

# c)
print("\nc)\n", sales.dtypes)

# d)
print("\nd)")
print("Dimensions (ndim):", sales.ndim)
print("Shape:", sales.shape)
print("Size:", sales.size)
print("Values:\n", sales.values)

# e)
print("\ne)\n", sales.tail(2))

# f)
print("\nf)\n", sales.iloc[:, :2])

# g)
sales2 = pd.DataFrame({
    "2018": [160000, 110000, 500000, 340000, 900000]
}, index=["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"])
print("\ng)\n", sales2)

# h)
print("\nh)", sales2.empty)



a) ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

b) ['2014', '2015', '2016', '2017']

c)
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object

d)
Dimensions (ndim): 2
Shape: (5, 4)
Size: 20
Values:
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]

e)
            2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

f)
             2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000

g)
            2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000

h) False


In [32]:
## --11--
import pandas as pd


data = {
    "2014": [100.5, 150.8, 200.9, 30000, 40000],
    "2015": [12000, 18000, 22000, 30000, 45000],
    "2016": [20000, 50000, 70000, 100000, 125000],
    "2017": [50000, 60000, 70000, 80000, 90000]
}
index = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]
sales = pd.DataFrame(data, index=index)

# a)
sales2 = pd.DataFrame({
    "2018": [160000, 110000, 500000, 340000, 900000]
}, index=["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"])
sales = pd.concat([sales, sales2], axis=1)

# b)
sales = sales.T

# c)
print("c)\n", sales.loc["2017"])

# d)
print("d)\n", sales.loc[["2017", "2018"], ["Madhu", "Ankit"]])

# e)
print("e)\n", sales.loc["2016", "Shruti"])

# f)
sales["Sumeet"] = [196.2, 37800, 52000, 78438, 38852]

# g)
sales = sales.drop("2014")

# h)
sales = sales.drop(columns="Kinshuk")

# i)
sales = sales.rename(columns={"Ankit": "Vivaan", "Madhu": "Shailesh"})

# j)
sales.loc["2018", "Shailesh"] = 100000

# k)
sales.to_csv("SalesFigures.csv", index=False, header=False)

# l)
sales_retrieved = pd.read_csv("SalesFigures.csv", header=None)
sales_retrieved.index = sales.index
sales_retrieved.columns = sales.columns

print("\nl)\n", sales_retrieved)


c)
 Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64
d)
          Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0
e)
 125000.0

l)
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [33]:
## Exercise 2
## ---13---
import pandas as pd
from sqlalchemy import create_engine

# a)
data = {
    "Item": ["TV", "TV", "TV", "AC"],
    "Company": ["LG", "VIDEOCON", "LG", "SONY"],
    "Rupees": [12000, 10000, 15000, 14000],
    "USD": [700, 650, 800, 750]
}
df = pd.DataFrame(data)

# b)
new_rows = pd.DataFrame([
    {"Item": "Fridge", "Company": "LG", "Rupees": 18000, "USD": 850},
    {"Item": "AC", "Company": "SONY", "Rupees": 16000, "USD": 780}
])
df = pd.concat([df, new_rows], ignore_index=True)

# c)
max_lg_tv = df[(df["Company"] == "LG") & (df["Item"] == "TV")]["Rupees"].max()
print("c) Maximum price of LG TV:", max_lg_tv)

# d)
total_rupees = df["Rupees"].sum()
print("d) Total Rupees of all products:", total_rupees)

# e)
median_sony_usd = df[df["Company"] == "SONY"]["USD"].median()
print("e) Median USD of SONY products:", median_sony_usd)

# f)
df_sorted = df.sort_values(by="Rupees", ascending=True)

engine = create_engine("mysql+pymysql://username:password@localhost:3306/your_database")

df_sorted.to_sql(name="product_table_sorted", con=engine, if_exists="replace", index=False)
print("f) Sorted data transferred to MySQL.")

# g)
df_new = pd.DataFrame({
    "Item": ["Washing Machine", "Microwave"],
    "Company": ["Samsung", "Panasonic"],
    "Rupees": [22000, 12500],
    "USD": [950, 610]
})

df_new.to_sql(name="new_product_table", con=engine, if_exists="replace", index=False)
print("g) New product data transferred to MySQL.")

c) Maximum price of LG TV: 15000
d) Total Rupees of all products: 85000
e) Median USD of SONY products: 765.0


ModuleNotFoundError: No module named 'pymysql'

In [ ]:
import pandas as pd
import numpy as np

# a)
data = {
    'Name': ['Anita', 'Ravi', 'Meena', 'Amit', 'Sana', 'Kunal'],
    'Degree': ['BCA', 'MBA', 'BCA', 'MBA', 'BTech', 'MBA'],
    'Marks': [85, np.nan, 91, 76, 88, np.nan]
}
df = pd.DataFrame(data)

# b)
print("b) Maximum marks in each Degree:")
print(df.groupby('Degree')['Marks'].max())

# c)
df['Marks'] = df['Marks'].fillna(76)

# d)
df.set_index('Name', inplace=True)

# e)
print("\ne) Name and Degree-wise average marks:")
print(df.groupby(['Name', 'Degree'])['Marks'].mean())

# f)
print("\nf) Number of students in MBA:")
print((df['Degree'] == 'MBA').sum())

# g)
print("\ng) Mode marks in BCA:")
print(df[df['Degree'] == 'BCA']['Marks'].mode())


In [ ]:
WEEK - 2

In [ ]:
TITANIC DATASET
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/titanic_train.csv')
df.shape


In [ ]:
[col for col in df.columns if df[col].isnull().sum() > 0]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(labels=['Survived'], axis=1), df['Survived'], test_size=0.3, random_state=0)
x_train.shape, x_test.shape

In [ ]:
constant_features_numeric = [feat for feat in x_train.select_dtypes(exclude='object').columns if x_train[feat].nunique() == 1]
print(f"Number of numeric constant features: {len(constant_features_numeric)}")


In [ ]:
x_train.drop(labels=constant_features_numeric, axis=1, inplace=True)
x_test.drop(labels=constant_features_numeric, axis=1, inplace=True)
x_train.shape, x_test.shape

In [ ]:
quasi_constant_features = []
for feature in x_train.columns:
    predominant = (x_train[feature].value_counts() / float(len(x_train))).sort_values(ascending=False).values[0]
    if predominant >= 0.998:
        quasi_constant_features.append(feature)

print(f"Number of quasi-constant features: {len(quasi_constant_features)}")


In [ ]:
x_train.drop(labels=quasi_constant_features, axis=1, inplace=True)
x_test.drop(labels=quasi_constant_features, axis=1, inplace=True)
x_train.shape, x_test.shape

In [ ]:
duplicated_feat = []
for i in range(0, len(x_train.columns)):
    col_1 = x_train.columns[i]
    for col_2 in x_train.columns[i + 1:]:
        if x_train[col_1].equals(x_train[col_2]):
            duplicated_feat.append(col_2)

In [ ]:
duplicated_features = set(duplicated_feat)
print(f"Number of duplicated features: {len(duplicated_features)}")

In [ ]:
x_train.drop(labels=duplicated_features, axis=1, inplace=True)
x_test.drop(labels=duplicated_features, axis=1, inplace=True)
x_train.shape, x_test.shape

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Select only numerical columns for correlation calculation
corrmat = x_train.select_dtypes(include=np.number).corr()

fig, ax = plt.subplots(figsize=(10, 10))
sns.heatmap(corrmat, vmax=1.0, square=True, cmap='coolwarm', annot=False, ax=ax)

plt.title('Correlation Heatmap of Features')
plt.show()

In [ ]:
grouped_features = []
correlated_features = set()
def correlation(dataset, threshold):
    column_corr = {}
    # Select only numerical columns for correlation calculation
    dataset_numeric = dataset.select_dtypes(include=np.number)
    corr_matrix = dataset_numeric.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]
                col_arr = column_corr.get(colname, [])
                col_arr.append(corr_matrix.columns[j])
                column_corr[colname] = col_arr
                correlated_features.add(corr_matrix.columns[j])
    return column_corr

In [ ]:
corr_features = correlation(x_train, 0.9)
correlated_features = set(filter(lambda x: x in x_train.columns, correlated_features))
print(f"Number of correlated features: {len(correlated_features)}")

In [ ]:
x_train.drop(labels=correlated_features, axis=1, inplace=True)
x_test.drop(labels=correlated_features, axis=1, inplace=True)

x_train.shape, x_test.shape


In [ ]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Select only numerical columns for mutual information calculation
x_train_numeric = x_train.select_dtypes(include=np.number)


mi = mutual_info_classif(x_train_numeric.fillna(0), y_train)

mi = pd.Series(mi, index=x_train_numeric.columns)
mi = mi.sort_values(ascending=False)

mi.plot.bar(figsize=(20, 8))
plt.title("Mutual Information Scores for Numeric Features")
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
from sklearn.model_selection import train_test_split

# Load Titanic subset with categorical & discrete vars
variables = ['pclass', 'survived', 'sex', 'sibsp', 'parch', 'embarked']
data = pd.read_csv(
    'https://www.openml.org/data/get_csv/16826755/phpMYEkMl',
    usecols=variables,
    na_values='?'
)

data.dropna(subset=['embarked'], inplace=True)
print(data.head())


In [ ]:
for col in ['pclass', 'sex', 'sibsp', 'parch', 'embarked']:
    contingency_table = pd.crosstab(data[col], data['survived'])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    print(f"Feature: {col}, Chi2: {chi2:.2f}, p-value: {p:.4f}")


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
from sklearn.model_selection import train_test_split

variables = ['pclass', 'survived', 'sex', 'sibsp', 'parch', 'embarked']
data = pd.read_csv(
    'https://www.openml.org/data/get_csv/16826755/phpMYEkMl',
    usecols=variables,
    na_values='?',
    )
data.dropna(subset=['embarked'], inplace=True)
data.head()


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    data.drop("survived", axis=1),
    data['survived'],
    test_size=0.3,
    random_state=0,
)


c = pd.crosstab(y_train, x_train['sex'])


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/titanic_train.csv')
df.shape


In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency


x_train, x_test, y_train, y_test = train_test_split(
    data.drop("Survived", axis=1),
    data['Survived'],
    test_size=0.3,
    random_state=0
)

# One-hot encode categorical features (Chi-square needs categorical or integer)
x_train_encoded = pd.get_dummies(x_train, drop_first=True)
x_test_encoded = pd.get_dummies(x_test, drop_first=True)

# Align columns between train and test
x_train_encoded, x_test_encoded = x_train_encoded.align(x_test_encoded, join='left', axis=1, fill_value=0)

chi_ls = []

for feature in x_train_encoded.columns:
    crosstab = pd.crosstab(y_train, x_train_encoded[feature])
    chi2, p_value, dof, expected = chi2_contingency(crosstab)
    chi_ls.append(p_value)


pd.Series(chi_ls, index=x_train_encoded.columns) \
    .sort_values(ascending=True) \
    .plot.bar(rot=90, figsize=(9, 5))

plt.ylabel("p value")
plt.title("Feature importance based on Chi-square test")
plt.show()


In [ ]:
SANTANDER CUSTOMER SATISFACTION

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
df = pd.read_csv('')
df.head()

In [ ]:

import pandas as pd
df = pd.read_csv('/Santander Customer Satisfaction_train.csv')
df.head()

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
nullColumns = [col for col in df.columns if df[col].isnull().sum()>0]
nullColumns

In [ ]:
categorical_cols = df.select_dtypes(include=['object']).columns

df = pd.get_dummies(df, columns=categorical_cols, drop_first = True)

df.head()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Santander Customer Satisfaction_test.csv')
df.head()

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Santander Customer Satisfaction_train (1).csv')
df.head()

In [ ]:
df.shape

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(labels=['TARGET', 'ID'], axis=1),
    df['TARGET'],
    test_size=0.3,
    random_state=0)

x_train.shape, x_test.shape

In [ ]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
corr_features = correlation(x_train, 0.8)
print('correlated features: ', len(set(corr_features)) )


In [ ]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

efs = EFS(estimator=lr,
          min_features=1,
          max_features=4,
          scoring='accuracy',
          cv=5)


In [ ]:
efs = efs.fit(x_train.fillna(0), y_train)

print('Best accuracy score: %.2f' % efs.best_score_)
print('Best subset (indices):', efs.best_idx_)
print('Best subset (corresponding names):', efs.best_feature_names_)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

titanic = sns.load_dataset('titanic')
numeric_data = titanic.select_dtypes(include=[np.number]).dropna()

scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_data)

pca = PCA()
pca_data = pca.fit_transform(scaled_data)

plt.figure(figsize=(8, 6))
plt.scatter(pca_data[:, 0], pca_data[:, 1], alpha=0.7, c='dodgerblue', edgecolor='k')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA: PC1 vs PC2 (Titanic Dataset)')
plt.grid(True)
plt.show()

loadings = pd.DataFrame(pca.components_.T,
                        columns=[f'PC{i+1}' for i in range(len(numeric_data.columns))],
                        index=numeric_data.columns)

pc1_top = loadings['PC1'].abs().sort_values(ascending=False)
pc2_top = loadings['PC2'].abs().sort_values(ascending=False)

print("\n(c) Top variables contributing to PC1:")
print(pc1_top.head())

print("\n(c) Top variables contributing to PC2:")
print(pc2_top.head())

explained_variance = pca.explained_variance_ratio_
pc1_pc2_variance = explained_variance[0] + explained_variance[1]
print(f"\n(d) Total variance explained by PC1 and PC2: {pc1_pc2_variance:.2%}")

cumulative_variance = np.cumsum(explained_variance)
num_components_80 = np.argmax(cumulative_variance >= 0.80) + 1
print(f"(e) Number of principal components to explain at least 80% of variance: {num_components_80}")


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
features_to_drop = list(set(corr_features) & set(x_train.columns))

x_train.drop(labels=features_to_drop, axis=1, inplace=True)
x_test.drop(labels=features_to_drop, axis=1, inplace=True)
x_train.shape, x_test.shape

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.ensemble import RandomForestClassifier
import numpy as np

sfs1 = SFS(RandomForestClassifier(n_jobs=4),
           k_features=5,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=3)
sfs1 = sfs1.fit(np.array(x_train.fillna(0)), y_train)

print('Best accuracy score: %.2f' % sfs1.k_score_)
print('Best subset (indices):', sfs1.k_feature_idx_)
print('Best subset (corresponding names):', sfs1.k_feature_names_)

In [ ]:
features_to_drop = list(set(corr_features) & set(x_train.columns))

x_train.drop(labels=features_to_drop, axis=1, inplace=True)
x_test.drop(labels=features_to_drop, axis=1, inplace=True)
x_train.shape, x_test.shape

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.ensemble import RandomForestClassifier
import numpy as np

sfs1 = SFS(RandomForestClassifier(n_jobs=4),
           k_features=5,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=3)
sfs1 = sfs1.fit(np.array(x_train.fillna(0)), y_train)

print('Best accuracy score: %.2f' % sfs1.k_score_)
print('Best subset (indices):', sfs1.k_feature_idx_)
print('Best subset (corresponding names):', sfs1.k_feature_names_)

In [ ]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
corr_features = correlation(x_train, 0.8)
print('correlated features: ', len(set(corr_features)) )

In [ ]:
features_to_drop = list(set(corr_features) & set(x_train.columns))

x_train.drop(labels=features_to_drop, axis=1, inplace=True)
x_test.drop(labels=features_to_drop, axis=1, inplace=True)
x_train.shape, x_test.shape

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.ensemble import RandomForestClassifier
import numpy as np

sfs1 = SFS(RandomForestClassifier(n_jobs=4),
           k_features=5,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=3)
sfs1 = sfs1.fit(np.array(x_train.fillna(0)), y_train)

print('Best accuracy score: %.2f' % sfs1.k_score_)
print('Best subset (indices):', sfs1.k_feature_idx_)
print('Best subset (corresponding names):', sfs1.k_feature_names_)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(labels=['TARGET', 'ID'], axis=1),
    df['TARGET'],
    test_size=0.3,
    random_state=0)

x_train.shape, x_test.shape

In [ ]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
corr_features = correlation(x_train, 0.8)
print('correlated features: ', len(set(corr_features)) )

In [ ]:
features_to_drop = list(set(corr_features) & set(x_train.columns))

x_train.drop(labels=features_to_drop, axis=1, inplace=True)
x_test.drop(labels=features_to_drop, axis=1, inplace=True)
x_train.shape, x_test.shape

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.ensemble import RandomForestClassifier
import numpy as np

sfs1 = SFS(RandomForestClassifier(n_jobs=4),
           k_features=5,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=3)
sfs1 = sfs1.fit(np.array(x_train.fillna(0)), y_train)

print('Best accuracy score: %.2f' % sfs1.k_score_)
print('Best subset (indices):', sfs1.k_feature_idx_)
print('Best subset (corresponding names):', sfs1.k_feature_names_)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(labels=['TARGET', 'ID'], axis=1),
    df['TARGET'],
    test_size=0.3,
    random_state=0)

x_train.shape, x_test.shape

In [ ]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
corr_features = correlation(x_train, 0.8)
print('correlated features: ', len(set(corr_features)) )

In [ ]:
features_to_drop = list(set(corr_features) & set(x_train.columns))

x_train.drop(labels=features_to_drop, axis=1, inplace=True)
x_test.drop(labels=features_to_drop, axis=1, inplace=True)
x_train.shape, x_test.shape

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.ensemble import RandomForestClassifier
import numpy as np

sfs1 = SFS(RandomForestClassifier(n_jobs=4),
           k_features=5,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=3)
sfs1 = sfs1.fit(np.array(x_train.fillna(0)), y_train)

print('Best accuracy score: %.2f' % sfs1.k_score_)
print('Best subset (indices):', sfs1.k_feature_idx_)
print('Best subset (corresponding names):', sfs1.k_feature_names_)

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Santander Customer Satisfaction_train (1).csv')
df.head()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(labels=['TARGET', 'ID'], axis=1),
    df['TARGET'],
    test_size=0.3,
    random_state=0)

x_train.shape, x_test.shape

In [ ]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
corr_features = correlation(x_train, 0.8)
print('correlated features: ', len(set(corr_features)) )

In [ ]:
features_to_drop = list(set(corr_features) & set(x_train.columns))

x_train.drop(labels=features_to_drop, axis=1, inplace=True)
x_test.drop(labels=features_to_drop, axis=1, inplace=True)
x_train.shape, x_test.shape

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.ensemble import RandomForestClassifier
import numpy as np

sfs1 = SFS(RandomForestClassifier(n_jobs=4),
           k_features=5,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=3)
sfs1 = sfs1.fit(np.array(x_train.fillna(0)), y_train)

print('Best accuracy score: %.2f' % sfs1.k_score_)
print('Best subset (indices):', sfs1.k_feature_idx_)
print('Best subset (corresponding names):', sfs1.k_feature_names_)