In [18]:
## --- 9 ---
import pandas as pd
data = {
    "2014": [100.5, 150.8, 200.9, 30000, 40000],
    "2015": [12000, 18000, 22000, 30000, 45000],
    "2016": [20000, 50000, 70000, 100000, 125000],
    "2017": [50000, 60000, 70000, 80000, 90000]
}
index = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]

sales = pd.DataFrame(data, index=index)
print("Sales DataFrame:\n", sales)


Sales DataFrame:
             2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000


In [22]:
## ---10---
import pandas as pd

#
data = {
    "2014": [100.5, 150.8, 200.9, 30000, 40000],
    "2015": [12000, 18000, 22000, 30000, 45000],
    "2016": [20000, 50000, 70000, 100000, 125000],
    "2017": [50000, 60000, 70000, 80000, 90000]
}
index = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]
sales = pd.DataFrame(data, index=index)

# a)
print("\na)", sales.index.tolist())

# b)
print("\nb)", sales.columns.tolist())

# c)
print("\nc)\n", sales.dtypes)

# d)
print("\nd)")
print("Dimensions (ndim):", sales.ndim)
print("Shape:", sales.shape)
print("Size:", sales.size)
print("Values:\n", sales.values)

# e)
print("\ne)\n", sales.tail(2))

# f)
print("\nf)\n", sales.iloc[:, :2])

# g)
sales2 = pd.DataFrame({
    "2018": [160000, 110000, 500000, 340000, 900000]
}, index=["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"])
print("\ng)\n", sales2)

# h)
print("\nh)", sales2.empty)



a) ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

b) ['2014', '2015', '2016', '2017']

c)
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object

d)
Dimensions (ndim): 2
Shape: (5, 4)
Size: 20
Values:
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]

e)
            2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

f)
             2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000

g)
            2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000

h) False


In [21]:
## --11--
import pandas as pd


data = {
    "2014": [100.5, 150.8, 200.9, 30000, 40000],
    "2015": [12000, 18000, 22000, 30000, 45000],
    "2016": [20000, 50000, 70000, 100000, 125000],
    "2017": [50000, 60000, 70000, 80000, 90000]
}
index = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]
sales = pd.DataFrame(data, index=index)

# a)
sales2 = pd.DataFrame({
    "2018": [160000, 110000, 500000, 340000, 900000]
}, index=["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"])
sales = pd.concat([sales, sales2], axis=1)

# b)
sales = sales.T

# c)
print("c)\n", sales.loc["2017"])

# d)
print("d)\n", sales.loc[["2017", "2018"], ["Madhu", "Ankit"]])

# e)
print("e)\n", sales.loc["2016", "Shruti"])

# f)
sales["Sumeet"] = [196.2, 37800, 52000, 78438, 38852]

# g)
sales = sales.drop("2014")

# h)
sales = sales.drop(columns="Kinshuk")

# i)
sales = sales.rename(columns={"Ankit": "Vivaan", "Madhu": "Shailesh"})

# j)
sales.loc["2018", "Shailesh"] = 100000

# k)
sales.to_csv("SalesFigures.csv", index=False, header=False)

# l)
sales_retrieved = pd.read_csv("SalesFigures.csv", header=None)
sales_retrieved.index = sales.index
sales_retrieved.columns = sales.columns

print("\nl)\n", sales_retrieved)


c)
 Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64
d)
          Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0
e)
 125000.0

l)
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
## Exercise 2
## ---13---
import pandas as pd
from sqlalchemy import create_engine

# a)
data = {
    "Item": ["TV", "TV", "TV", "AC"],
    "Company": ["LG", "VIDEOCON", "LG", "SONY"],
    "Rupees": [12000, 10000, 15000, 14000],
    "USD": [700, 650, 800, 750]
}
df = pd.DataFrame(data)

# b)
new_rows = pd.DataFrame([
    {"Item": "Fridge", "Company": "LG", "Rupees": 18000, "USD": 850},
    {"Item": "AC", "Company": "SONY", "Rupees": 16000, "USD": 780}
])
df = pd.concat([df, new_rows], ignore_index=True)

# c)
max_lg_tv = df[(df["Company"] == "LG") & (df["Item"] == "TV")]["Rupees"].max()
print("c) Maximum price of LG TV:", max_lg_tv)

# d)
total_rupees = df["Rupees"].sum()
print("d) Total Rupees of all products:", total_rupees)

# e)
median_sony_usd = df[df["Company"] == "SONY"]["USD"].median()
print("e) Median USD of SONY products:", median_sony_usd)

# f)
df_sorted = df.sort_values(by="Rupees", ascending=True)

engine = create_engine("mysql+pymysql://username:password@localhost:3306/your_database")

df_sorted.to_sql(name="product_table_sorted", con=engine, if_exists="replace", index=False)
print("f) Sorted data transferred to MySQL.")

# g)
df_new = pd.DataFrame({
    "Item": ["Washing Machine", "Microwave"],
    "Company": ["Samsung", "Panasonic"],
    "Rupees": [22000, 12500],
    "USD": [950, 610]
})

df_new.to_sql(name="new_product_table", con=engine, if_exists="replace", index=False)
print("g) New product data transferred to MySQL.")

In [ ]:
import pandas as pd
import numpy as np

# a)
data = {
    'Name': ['Anita', 'Ravi', 'Meena', 'Amit', 'Sana', 'Kunal'],
    'Degree': ['BCA', 'MBA', 'BCA', 'MBA', 'BTech', 'MBA'],
    'Marks': [85, np.nan, 91, 76, 88, np.nan]
}
df = pd.DataFrame(data)

# b)
print("b) Maximum marks in each Degree:")
print(df.groupby('Degree')['Marks'].max())

# c)
df['Marks'] = df['Marks'].fillna(76)

# d)
df.set_index('Name', inplace=True)

# e)
print("\ne) Name and Degree-wise average marks:")
print(df.groupby(['Name', 'Degree'])['Marks'].mean())

# f)
print("\nf) Number of students in MBA:")
print((df['Degree'] == 'MBA').sum())

# g)
print("\ng) Mode marks in BCA:")
print(df[df['Degree'] == 'BCA']['Marks'].mode())
